<!DOCTYPE html>
<html>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="CSS/Style.css">
    <link rel="stylesheet" href="CSS/BootStrap/bootstrap.css">

    <?php
       include 'Header.php';
    ?>

    <body>
        <div class="container" id="background">
            <div class="TitleContainer">
                <h1>Velcome to webbshop</h1>
                <h2>This is a store for seling different kind of office products</h2>
            </div>

            <div id="ProductContainer">
                <p>Infocontainer</p>
            </div>
        </div>
    </body>

    <?php
       include 'footer.php';
    ?>

</html>