<!DOCTYPE html>
<html>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="CSS/Style.css">
    <link rel="stylesheet" href="CSS/BootStrap/bootstrap.css">

    <?php include 'Header.php'; ?>

    <body>
        <div class="container" id="background">
            <div class="TitleContainer">
                <h1>Contacts</h1>
                <h2>Here can you find different ways to contact the companystoretemplate</h2>
            </div>

            <div id="ProductContainer">
                <a href="url">Linkedin: </a> </br>
                <a href="mailto:webmaster@example.com">Jon Doe</a> </br>
                <a href="tel:123-456-7890">123-456-7890</a> </br>
            </div>
        </div>
    </body>

    <?php include 'footer.php';?>

</html>